import {test} from 'node:test';import assert from 'node:assert/strict';import {installFakeDom} from './fakedom.mjs';
import {widgetPrefs,clockWidget,weatherWidget,WidgetSlots,loadWidgets,saveWidgets} from '../src/core/widgets.ts';
const store=()=>{const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)}};
const flush=()=>new Promise(resolve=>setImmediate(resolve));
test('widget preferences validate ranges, zones and reorder without duplicates',()=>{const p=widgetPrefs({order:['weather','weather','bad'],latitude:999,longitude:0,secondZone:'not/a/timezone'});assert.deepEqual(p.order,['weather','clock']);assert.equal(p.latitude,null);assert.equal(p.longitude,0);assert.equal(p.secondZone,'');const s=store();saveWidgets({...p,latitude:0,clock:false},s);assert.equal(loadWidgets(s).latitude,0);assert.equal(loadWidgets(s).clock,false);});
test('clock exposes local time plus an optional real IANA timezone',async()=>{const p=widgetPrefs({secondZone:'Asia/Tokyo'});const d=await clockWidget(p,()=>new Date('2026-10-09T06:00:00Z')).poll();assert.ok(d.label.includes('Tokyo'));assert.ok(d.title.includes('Asia/Tokyo'));assert.equal(d.stale,false);});
test('weather caches for 60 minutes, keeps last value stale offline, and rejects malformed payloads',async()=>{let n=1,calls=0,offline=false;const s=store();const f=async()=>{calls++;if(offline)throw new Error('offline');return{ok:true,json:async()=>({current:{temperature_2m:24.8,weather_code:0}})}};const w=weatherWidget(widgetPrefs({latitude:0,longitude:0}),f,s,()=>n);assert.equal((await w.poll()).label,'25°C');n+=3599999;assert.equal((await w.poll()).stale,false);assert.equal(calls,1);n++;offline=true;assert.equal((await w.poll()).stale,true);assert.equal(calls,2);const bad=weatherWidget(widgetPrefs({latitude:1,longitude:1}),async()=>({ok:true,json:async()=>({current:{temperature_2m:'bad'}})}),store(),()=>n);await assert.rejects(()=>bad.poll(),/Invalid weather/);});
test('one-hour simulated soak: no overlapping polls; disabled pills have no timer or future polling',async()=>{const dom=installFakeDom(),host=dom.root();let time=0,id=0;const timers=new Map();let requests=0,updates=0;const s=store();const p=widgetPrefs({weather:true,latitude:52.52,longitude:13.41});const runtime=new WidgetSlots(host,{set:(fn,ms)=>{const x=++id;timers.set(x,{fn,ms});return x;},clear:x=>timers.delete(x)},(which,p,signal)=>{const w=which==='clock'?clockWidget(p,()=>new Date(time)):weatherWidget(p,async()=>{requests++;return{ok:true,json:async()=>({current:{temperature_2m:20,weather_code:0}})}},s,()=>time,signal);const render=w.render;w.render=(el,data)=>{if(el.textContent!==data.label)updates++;render(el,data)};return w});runtime.sync(p);await flush();for(let sec=1;sec<=3600;sec++){time=sec*1000;for(const t of timers.values())if(time%t.ms===0)t.fn();await flush();}assert.equal(requests,2);assert.ok(updates<70,'DOM labels should not redraw on every clock poll');assert.equal(timers.size,2);runtime.sync({...p,weather:false});await flush();const before=requests;for(const t of timers.values())t.fn();await flush();assert.equal(requests,before);assert.equal(timers.size,1);assert.equal(host.children.length,1);runtime.destroy();assert.equal(timers.size,0);});
test('disabling a pill while its request is pending cannot resurrect its DOM',async()=>{const dom=installFakeDom(),host=dom.root();let resolve;const runtime=new WidgetSlots(host,{set:()=>1,clear:()=>{}},id=>({id,intervalMs:1000,poll:()=>new Promise(r=>resolve=r),render:(el,d)=>el.textContent=d.label}));runtime.sync(widgetPrefs({clock:true}));runtime.sync(widgetPrefs({clock:false}));resolve({label:'late',title:'late',stale:false});await flush();assert.equal(host.children.length,0);runtime.destroy();});
