// Runs only when CI explicitly supplies the verified native engine executable.
use super::*;
use windows::Win32::System::Threading::{OpenProcess,GetExitCodeProcess,PROCESS_QUERY_LIMITED_INFORMATION};
struct Fixture(Child);impl Drop for Fixture{fn drop(&mut self){let _=self.0.kill();let _=self.0.wait();}}
fn alive(pid:u32)->bool{unsafe{let Ok(h)=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,false,pid)else{return false;};let mut code=0;let ok=GetExitCodeProcess(h,&mut code).is_ok();let _=CloseHandle(h);ok&&code==259}}
fn profile(url:String)->Profile{Profile{id:"fixture".into(),label:"Offline test provider".into(),base_url:url,model_id:"fixture-model".into(),protocol:"openai-compatible".into(),no_auth:false,params:Default::default(),input_usd_per_million:Some(1.0),output_usd_per_million:Some(2.0),cached_input_usd_per_million:None}}
async fn ready(c:&Connection){for _ in 0..120{if api(c,reqwest::Method::GET,"/global/health",None,Duration::from_secs(2)).await.is_ok(){return;}tokio::time::sleep(Duration::from_millis(250)).await;}panic!("Verified engine did not start");}
async fn make_session(c:&Connection)->String{api(c,reqwest::Method::POST,"/session",Some(json!({"title":"Nova CI","permission":rules("normal")})),Duration::from_secs(120)).await.expect("Native session create")["id"].as_str().unwrap().into()}
async fn task(c:&Connection,id:&str,text:&str)->Value{api(c,reqwest::Method::POST,&format!("/session/{id}/message"),Some(json!({"model":{"providerID":"nova","modelID":"fixture-model"},"parts":[{"type":"text","text":text}]})),Duration::from_secs(120)).await.expect("Real engine / mock provider task")}
async fn permission(c:&Connection)->Value{for _ in 0..200{let list=api(c,reqwest::Method::GET,"/permission",None,Duration::from_secs(5)).await.unwrap();if let Some(p)=list.as_array().and_then(|a|a.first()){return p.clone();}tokio::time::sleep(Duration::from_millis(50)).await;}panic!("Expected a native permission before execution");}
async fn shell_permission(c:&Connection)->Value{for _ in 0..8{let p=permission(c).await;if p["permission"]=="bash"{return p;}assert_eq!(p["permission"],"external_directory","Unexpected pre-shell permission");decide(c,&p,"once").await;}panic!("Shell gate missing");}
async fn decide(c:&Connection,p:&Value,reply:&str){api(c,reqwest::Method::POST,&format!("/permission/{}/reply",p["id"].as_str().unwrap()),Some(json!({"reply":reply})),Duration::from_secs(10)).await.unwrap();}
#[test]
fn real_engine_two_providers_files_shell_denials_history_and_process_cleanup(){
 if std::env::var("NOVA_ENGINE_TEST_EXE").is_err(){return;}
 tokio::runtime::Builder::new_current_thread().enable_all().build().unwrap().block_on(async{
  let base=std::env::temp_dir().join(format!("nova-engine-ci-{}",std::process::id()));std::fs::create_dir_all(&base).unwrap();let cwd=base.join("project");std::fs::create_dir_all(&cwd).unwrap();
  let script=PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../tests/mock-engine-provider.mjs");let port_file=base.join("provider.port");
  let server=Command::new("node").arg(&script).arg(&port_file).arg(&cwd).arg("fake-test-key-one").stdin(Stdio::null()).stdout(Stdio::null()).stderr(Stdio::null()).spawn().unwrap();let _fixture=Fixture(server);
  for _ in 0..100{if port_file.is_file(){break;}tokio::time::sleep(Duration::from_millis(50)).await;}let port=std::fs::read_to_string(&port_file).expect("Mock server port");let p=profile(format!("http://127.0.0.1:{port}/v1"));
  let mut process=spawn(&p,"fake-test-key-one".into(),&cwd,42,&base.join("runtime")).unwrap();let c=process.connection.clone();ready(&c).await;
  let tools=api(&c,reqwest::Method::GET,"/experimental/tool/ids",None,Duration::from_secs(120)).await.expect("Plugin/tool registry");assert!(tools.as_array().unwrap().iter().any(|v|v=="nova_recycle"));assert!(tools.as_array().unwrap().iter().any(|v|v=="nova_history_search"));
  let id=make_session(&c).await;let c2=c.clone();let id2=id.clone();let running=tokio::spawn(async move{task(&c2,&id2,"WRITE_FIXTURE").await});let pending=permission(&c).await;
  assert_eq!(pending["permission"],"edit");assert!(pending["metadata"]["diff"].as_str().unwrap().contains("Nova real engine wrote this."));assert!(!cwd.join("written.txt").exists());decide(&c,&pending,"once").await;running.await.unwrap();assert_eq!(std::fs::read_to_string(cwd.join("written.txt")).unwrap(),"Nova real engine wrote this.");
  let id=make_session(&c).await;let c2=c.clone();let id2=id.clone();let running=tokio::spawn(async move{task(&c2,&id2,"SHELL_FIXTURE").await});let pending=shell_permission(&c).await;assert_eq!(pending["permission"],"bash");assert!(!cwd.join("shell.txt").exists());decide(&c,&pending,"reject").await;running.await.unwrap();assert!(!cwd.join("shell.txt").exists());
  let id=make_session(&c).await;let c2=c.clone();let id2=id.clone();let running=tokio::spawn(async move{task(&c2,&id2,"SHELL_FIXTURE").await});let pending=shell_permission(&c).await;assert!(!cwd.join("shell.txt").exists());decide(&c,&pending,"once").await;running.await.unwrap();assert_eq!(std::fs::read_to_string(cwd.join("shell.txt")).unwrap(),"approved only");
  let id=make_session(&c).await;let c2=c.clone();let id2=id.clone();let running=tokio::spawn(async move{task(&c2,&id2,"FORMAT_DENY_FIXTURE").await});let pending=shell_permission(&c).await;assert_eq!(pending["permission"],"bash");decide(&c,&pending,"reject").await;running.await.unwrap();
  let id=make_session(&c).await;task(&c,&id,"My marker is NOVA_MEMORY_271").await;let saved=api(&c,reqwest::Method::GET,&format!("/session/{id}/message"),None,Duration::from_secs(10)).await.unwrap();assert!(saved.to_string().contains("NOVA_MEMORY_271"));assert!(!saved.to_string().contains("fake-test-key-one"));
  let id=make_session(&c).await;let c2=c.clone();let id2=id.clone();let running=tokio::spawn(async move{task(&c2,&id2,"CHILD_FIXTURE").await});let pending=shell_permission(&c).await;decide(&c,&pending,"once").await;running.await.unwrap();let pid=std::fs::read_to_string(cwd.join("child.pid")).unwrap().trim().parse::<u32>().unwrap();assert!(alive(pid));let parent_pid=process.child.id();let _=process.child.kill();drop(process.job);let _=process.child.wait();tokio::time::sleep(Duration::from_millis(200)).await;assert!(!alive(pid));assert!(!alive(parent_pid));
  // A second endpoint/key exercises the real provider adapter, not a frontend stub.
  let port_file=base.join("provider2.port");let server=Command::new("node").arg(&script).arg(&port_file).arg(&cwd).arg("fake-test-key-two").stdin(Stdio::null()).stdout(Stdio::null()).stderr(Stdio::null()).spawn().unwrap();let _fixture2=Fixture(server);for _ in 0..100{if port_file.is_file(){break;}tokio::time::sleep(Duration::from_millis(50)).await;}let port=std::fs::read_to_string(port_file).unwrap();let p=profile(format!("http://127.0.0.1:{port}/v1"));let process=spawn(&p,"fake-test-key-two".into(),&cwd,43,&base.join("runtime")).unwrap();let c=process.connection.clone();ready(&c).await;let id=make_session(&c).await;let result=task(&c,&id,"Second provider works").await;assert!(result.to_string().contains("Fixture task complete"));drop(process);
 });
}
