#!/usr/bin/swift
// PiExtensionTests.swift — standalone test script for Pi extension support.
// Run from repo root:
//   swift NotchBuddy/Tests/PiExtensionTests.swift

import Foundation

var passed = 0
var failed = 0

func check(_ name: String, _ condition: Bool) {
    if condition {
        print("  PASS \(name)")
        passed += 1
    } else {
        print("  FAIL \(name)")
        failed += 1
    }
}

print("PiExtensionTests")
print("================")

// 1. Extension path & URL
let home = FileManager.default.homeDirectoryForCurrentUser
let expectedPath = home.appendingPathComponent(".pi/agent/extensions/coucou.ts").path
check("1. Extension path is ~/.pi/agent/extensions/coucou.ts",
      expectedPath.hasSuffix("/.pi/agent/extensions/coucou.ts"))

// 2. Template content generator simulation
func generatePiExtension(hookPath: String) -> String {
    let path = hookPath
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "'", with: "\\'")
    return """
// Coucou hook plugin for Pi — generated by Coucou.app
// Forwards every event to the Coucou notch (fire-and-forget, never blocks).
import { spawn } from 'node:child_process';

const HOOK = '\(path)';

function forward(hook_event_name: string, fields: Record<string, unknown>): void {
  try {
    const payload = JSON.stringify({ hook_event_name, ...fields });
    const p = spawn('/bin/sh', [HOOK, '--agent', 'pi'], {
      stdio: ['pipe', 'ignore', 'ignore'],
      detached: true,
    });
    p.on('error', () => {});
    p.on('close', () => {});
    (p.stdin as import('node:stream').Writable)?.on('error', () => {});
    (p.stdin as import('node:stream').Writable)?.write(payload + '\\n');
    (p.stdin as import('node:stream').Writable)?.end();
    p.unref();
  } catch {
    // Never block Pi
  }
}

function textContent(content: unknown): string {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return '';
  const texts: string[] = [];
  for (const part of content) {
    if (
      part !== null &&
      typeof part === 'object' &&
      'type' in part &&
      part.type === 'text' &&
      'text' in part &&
      typeof part.text === 'string'
    ) {
      texts.push(part.text);
    }
  }
  return texts.join('\\n').trim();
}

export default function (pi: any): void {
  let lastAssistantMessage = '';

  pi.on('session_start', (_event: unknown, ctx: any) => {
    lastAssistantMessage = '';
    forward('SessionStart', {
      session_id: ctx?.sessionManager?.getSessionId?.() || '',
      cwd: ctx?.cwd ?? process.cwd(),
    });
  });

  pi.on('before_agent_start', (event: any, ctx: any) => {
    lastAssistantMessage = '';
    forward('UserPromptSubmit', {
      session_id: ctx?.sessionManager?.getSessionId?.() || '',
      cwd: ctx?.cwd ?? process.cwd(),
      prompt: event?.prompt || '',
    });
  });

  pi.on('tool_execution_start', (event: any, ctx: any) => {
    forward('PreToolUse', {
      session_id: ctx?.sessionManager?.getSessionId?.() || '',
      cwd: ctx?.cwd ?? process.cwd(),
      tool_name: typeof event.toolName === 'string' ? event.toolName : '',
      tool_input: event.args ?? null,
    });
  });

  pi.on('tool_execution_end', (event: any, ctx: any) => {
    forward('PostToolUse', {
      session_id: ctx?.sessionManager?.getSessionId?.() || '',
      cwd: ctx?.cwd ?? process.cwd(),
      tool_name: typeof event.toolName === 'string' ? event.toolName : '',
    });
  });

  pi.on('message_end', (event: any) => {
    if (event?.message?.role === 'assistant') {
      const text = textContent(event.message.content);
      if (text) {
        lastAssistantMessage = text;
      }
    }
  });

  pi.on('agent_end', (_event: unknown, ctx: any) => {
    forward('Stop', {
      session_id: ctx?.sessionManager?.getSessionId?.() || '',
      cwd: ctx?.cwd ?? process.cwd(),
      last_assistant_message: lastAssistantMessage,
    });
  });

  pi.on('session_shutdown', (_event: unknown, ctx: any) => {
    forward('SessionEnd', {
      session_id: ctx?.sessionManager?.getSessionId?.() || '',
      cwd: ctx?.cwd ?? process.cwd(),
    });
  });
}
"""
}

let template = generatePiExtension(hookPath: "/Applications/NotchBuddy.app/Contents/Resources/nb-hook")

check("2. Template header comment present", template.contains("Coucou hook plugin for Pi — generated by Coucou.app"))
check("3. Template contains --agent pi argument", template.contains("'--agent', 'pi'"))
check("4. Template contains session_start hook", template.contains("pi.on('session_start'"))
check("5. Template contains before_agent_start hook", template.contains("pi.on('before_agent_start'"))
check("6. Template contains tool_execution_start hook", template.contains("pi.on('tool_execution_start'"))
check("7. Template contains tool_execution_end hook", template.contains("pi.on('tool_execution_end'"))
check("8. Template contains message_end hook", template.contains("pi.on('message_end'"))
check("9. Template contains agent_end hook", template.contains("pi.on('agent_end'"))
check("10. Template contains session_shutdown hook", template.contains("pi.on('session_shutdown'"))
check("11. Template has fire-and-forget error swallowing", template.contains("// Never block Pi"))

// 12. Detection logic
func isInstalled(content: String) -> Bool {
    return content.contains("nb-hook") && content.contains("'pi'")
}

check("12. Valid generated content detected as installed", isInstalled(content: template))
check("13. Unrelated file not detected as installed", !isInstalled(content: "console.log('hello world');"))
check("14. Partial match without pi not detected", !isInstalled(content: "const HOOK = 'nb-hook';"))

print("\nSummary: \(passed) passed, \(failed) failed")
if failed > 0 {
    exit(1)
}
