import {h,clear} from '../views/dom';
import {loadWidgets,saveWidgets,searchCities,ipLocation,type City} from '../core/widgets';
export function widgetsSection(){let prefs=loadWidgets();const panel=h('section',{},h('h2',{text:'Widgets'}),h('p',{class:'hint',text:'Header pills update independently from the mascot. Disabled pills stop polling. Weather uses a 60-minute cache and keeps stale values offline.'}));const order=h('div',{class:'widget-settings-order'});const zone=h('input',{type:'text',value:prefs.secondZone,placeholder:'Optional: Asia/Kolkata'}) as HTMLInputElement;const latitude=h('input',{type:'number',min:-90,max:90,step:'any',value:prefs.latitude==null?'':String(prefs.latitude)}) as HTMLInputElement;const longitude=h('input',{type:'number',min:-180,max:180,step:'any',value:prefs.longitude==null?'':String(prefs.longitude)}) as HTMLInputElement;const city=h('input',{type:'text',placeholder:'Search a city'}) as HTMLInputElement;const results=h('div',{class:'widget-city-results'});const notice=h('p',{class:'hint',role:'status'});let location=prefs.location;
 const field=(label:string,control:HTMLElement)=>h('label',{class:'engine-field'},h('span',{text:label}),control);
 const persist=()=>{try{saveWidgets(prefs);notice.textContent='Widget settings saved.';}catch{notice.textContent='Widget settings could not be saved. Check app storage permissions.';}};
 const draw=()=>{clear(order);for(const id of prefs.order){const checkbox=h('input',{type:'checkbox','aria-label':'Enable '+id}) as HTMLInputElement;checkbox.checked=prefs[id];checkbox.addEventListener('change',()=>{prefs[id]=checkbox.checked;persist();});const move=(direction:number)=>{const at=prefs.order.indexOf(id),to=at+direction;if(to<0||to>=prefs.order.length)return;[prefs.order[at],prefs.order[to]]=[prefs.order[to],prefs.order[at]];persist();draw();};const up=h('button',{text:'↑',title:'Move '+id+' earlier',onclick:()=>move(-1)}),down=h('button',{text:'↓',title:'Move '+id+' later',onclick:()=>move(1)});(up as HTMLButtonElement).disabled=prefs.order.indexOf(id)===0;(down as HTMLButtonElement).disabled=prefs.order.indexOf(id)===prefs.order.length-1;order.append(h('div',{class:'widget-settings-row'},h('label',{},checkbox,' '+(id==='clock'?'Clock':'Weather')),h('div',{},up,down)));}};
 const use=(c:City)=>{latitude.value=String(c.latitude);longitude.value=String(c.longitude);location=c.name+(c.country?', '+c.country:'');notice.textContent='Selected '+location+'; click Save widget details.';clear(results);};
 const lookup=h('button',{text:'Find city',onclick:()=>void(async()=>{try{clear(results);const cities=await searchCities(city.value);if(!cities.length)notice.textContent='No city found. Enter manual coordinates.';for(const c of cities)results.append(h('button',{text:c.name+', '+c.country,onclick:()=>use(c)}));}catch(e){notice.textContent=String(e).replace(/^Error:\s*/,'');}})()});
 const ip=h('button',{text:'Use approximate IP location',onclick:()=>void(async()=>{try{if(!window.confirm('Estimate your location using ipapi.co? Your public IP is shared with that service; the result may be inaccurate.'))return;use(await ipLocation());}catch(e){notice.textContent=String(e).replace(/^Error:\s*/,'');}})()});
 const save=h('button',{class:'primary',text:'Save widget details',onclick:()=>{try{if(zone.value.trim())new Intl.DateTimeFormat('en',{timeZone:zone.value.trim()});const lat=latitude.value.trim()===''?null:Number(latitude.value),lon=longitude.value.trim()===''?null:Number(longitude.value);if((lat==null)!==(lon==null)||lat!=null&&(!Number.isFinite(lat)||lat < -90||lat >90)||lon!=null&&(!Number.isFinite(lon)||lon < -180||lon >180))throw new Error('Enter both latitude/longitude in their valid ranges');prefs={...prefs,secondZone:zone.value.trim(),latitude:lat,longitude:lon,location};persist();}catch(e){notice.textContent=String(e).replace(/^Error:\s*/,'');}}});
 latitude.addEventListener('input',()=>location='');longitude.addEventListener('input',()=>location='');panel.append(order,field('Second clock timezone (IANA name)',zone),h('details',{class:'engine-optional'},h('summary',{text:'Weather location'}),field('City',city),h('div',{class:'engine-profile-actions'},lookup,ip),results,h('div',{class:'engine-pricing'},field('Latitude',latitude),field('Longitude',longitude)),h('p',{class:'hint',text:'Open-Meteo receives these coordinates when weather is enabled. IP lookup happens only when you click its button.'})),save,notice);draw();return panel;
}
