// Independent DOM polling; never participates in the Canvas animation loop.
export type WidgetId='clock'|'weather';
export interface WidgetData {label:string;title:string;stale:boolean}
export interface Widget<Data> {id:WidgetId;intervalMs:number;poll():Promise<Data>;render(el:HTMLElement,data:Data):void}
export interface WidgetPrefs {version:1;order:WidgetId[];clock:boolean;weather:boolean;secondZone:string;latitude:number|null;longitude:number|null;location:string}
export const WIDGET_PREFS_KEY='nova-widgets-v1';
export const DEFAULT_WIDGET_PREFS:WidgetPrefs={version:1,order:['clock','weather'],clock:true,weather:false,secondZone:'',latitude:null,longitude:null,location:''};
export interface Store {getItem(k:string):string|null;setItem(k:string,v:string):void}
export function widgetPrefs(raw:unknown):WidgetPrefs {const p=(raw&&typeof raw==='object'?raw:{}) as Partial<WidgetPrefs>;const valid=(v:unknown,min:number,max:number)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max?v:null;let secondZone=typeof p.secondZone==='string'?p.secondZone.slice(0,80):'';try{if(secondZone)new Intl.DateTimeFormat('en',{timeZone:secondZone});}catch{secondZone='';}const ids=['clock','weather'] as const;const order=[...new Set((Array.isArray(p.order)?p.order:[]).filter((x):x is WidgetId=>ids.includes(x)))];for(const id of ids)if(!order.includes(id))order.push(id);return{version:1,order,clock:p.clock!==false,weather:p.weather===true,secondZone,latitude:valid(p.latitude,-90,90),longitude:valid(p.longitude,-180,180),location:typeof p.location==='string'?p.location.slice(0,120):''};}
export function loadWidgets(store?:Store):WidgetPrefs{try{return widgetPrefs(JSON.parse((store??localStorage).getItem(WIDGET_PREFS_KEY)||'{}'));}catch{return widgetPrefs({});}}
export function saveWidgets(p:WidgetPrefs,store?:Store){(store??localStorage).setItem(WIDGET_PREFS_KEY,JSON.stringify(widgetPrefs(p)));if(typeof window.dispatchEvent==='function')window.dispatchEvent(new Event('nova-widgets-changed'));}
export function renderWidget(el:HTMLElement,data:WidgetData){if(el.textContent!==data.label)el.textContent=data.label;el.title=data.title+(data.stale?' · stale / offline':'');el.classList.toggle('stale',data.stale);el.setAttribute('aria-label',el.title);}
export function clockWidget(p:WidgetPrefs,now=()=>new Date()):Widget<WidgetData>{const fmt=(date:Date,zone?:string)=>new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',...(zone?{timeZone:zone}:{})}).format(date);return{id:'clock',intervalMs:1000,async poll(){const date=now();const local=fmt(date);const second=p.secondZone?`${p.secondZone.split('/').at(-1)?.replaceAll('_',' ')} ${fmt(date,p.secondZone)}`:'';return{label:local+(second?' · '+second:''),title:'Local time'+(second?' · '+p.secondZone:''),stale:false};},render:renderWidget};}
const CACHE_KEY='nova-weather-cache-v1';
function weatherDescription(code:number){if(code===0)return'Clear';if(code<=3)return'Cloudy';if(code<=48)return'Fog';if(code<=67)return'Rain';if(code<=77)return'Snow';if(code<=82)return'Showers';if(code<=86)return'Snow showers';return'Thunderstorm';}
export function weatherWidget(p:WidgetPrefs,fetcher:typeof fetch=fetch,store:Store=localStorage,now=Date.now,signal?:AbortSignal):Widget<WidgetData>{
 const cached=()=>{try{const c=JSON.parse(store.getItem(CACHE_KEY)||'null');return c&&c.latitude===p.latitude&&c.longitude===p.longitude&&typeof c.updated==='number'&&typeof c.data?.label==='string'&&typeof c.data?.title==='string'&&c.data.label.length<120&&c.data.title.length<500?c:null;}catch{return null;}};
 return{id:'weather',intervalMs:3600000,async poll(){if(p.latitude==null||p.longitude==null)return{label:'Set weather location',title:'Open Settings → Widgets to set a location',stale:false};const old=cached();if(old&&now()-old.updated>=0&&now()-old.updated<3600000)return{...old.data,stale:false};try{const q=new URLSearchParams({latitude:String(p.latitude),longitude:String(p.longitude),current:'temperature_2m,weather_code',timezone:'auto'});const r=await fetcher('https://api.open-meteo.com/v1/forecast?'+q,{signal:signal?AbortSignal.any([signal,AbortSignal.timeout(10000)]):AbortSignal.timeout(10000),credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw new Error('Weather unavailable');const v=await r.json();const temp=v.current?.temperature_2m,code=v.current?.weather_code;if(typeof temp!=='number'||!Number.isFinite(temp)||temp < -100||temp > 80||typeof code!=='number'||!Number.isInteger(code)||code < 0||code > 99)throw new Error('Invalid weather response');const data={label:Math.round(temp)+'°C',title:`${p.location||'Weather'} · ${weatherDescription(code)} · updated ${new Date(now()).toLocaleTimeString()}`,stale:false};try{store.setItem(CACHE_KEY,JSON.stringify({latitude:p.latitude,longitude:p.longitude,updated:now(),data}));}catch{/* A full cache must not stop the widget. */}return data;}catch(e){if(signal?.aborted)throw e;if(old)return{...old.data,stale:true};throw e;}},render:renderWidget};
}
export interface City {name:string;country:string;latitude:number;longitude:number}
export async function searchCities(name:string,fetcher:typeof fetch=fetch):Promise<City[]>{if(name.trim().length<2)throw new Error('Enter a city name');const r=await fetcher('https://geocoding-api.open-meteo.com/v1/search?'+new URLSearchParams({name:name.trim(),count:'5',language:'en',format:'json'}),{signal:AbortSignal.timeout(10000),credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw new Error('City search unavailable');const v=await r.json();return(v.results||[]).filter((x:any)=>typeof x.name==='string'&&typeof x.country==='string'&&Number.isFinite(x.latitude)&&Number.isFinite(x.longitude)).map((x:any)=>({name:x.name,country:x.country,latitude:x.latitude,longitude:x.longitude}));}
export async function ipLocation(fetcher:typeof fetch=fetch):Promise<City>{const r=await fetcher('https://ipapi.co/json/',{signal:AbortSignal.timeout(10000),credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw new Error('IP estimate unavailable; use city search or manual coordinates');const v=await r.json();if(v.error||!Number.isFinite(v.latitude)||!Number.isFinite(v.longitude))throw new Error('IP estimate unavailable; use manual coordinates');return{name:String(v.city||'IP estimate'),country:String(v.country_name||''),latitude:v.latitude,longitude:v.longitude};}
export interface TimerDriver {set(fn:()=>void,ms:number):number;clear(id:number):void}
interface Active {widget:Widget<WidgetData>;el:HTMLElement;timer:number;abort:AbortController;busy:boolean;last:WidgetData|null}
export class WidgetSlots {
 private active=new Map<WidgetId,Active>();private generation=0;
 private host:HTMLElement; private timers:TimerDriver; private factory?: (id:WidgetId,p:WidgetPrefs,signal:AbortSignal)=>Widget<WidgetData>;
 constructor(host:HTMLElement,timers:TimerDriver={set:(f,n)=>window.setInterval(f,n),clear:n=>window.clearInterval(n)},factory?:(id:WidgetId,p:WidgetPrefs,signal:AbortSignal)=>Widget<WidgetData>){this.host=host;this.timers=timers;this.factory=factory;}
 sync(p:WidgetPrefs){this.destroy();const generation=this.generation;for(const id of p.order){if(!p[id])continue;const el=document.createElement('span');el.className='widget-pill';el.textContent=id==='clock'?'Clock…':'Weather…';this.host.append(el);const abort=new AbortController();const widget=this.factory?this.factory(id,p,abort.signal):id==='clock'?clockWidget(p):weatherWidget(p,fetch,localStorage,Date.now,abort.signal);const entry:Active={widget,el,timer:0,abort,busy:false,last:null};this.active.set(id,entry);const poll=async()=>{if(entry.busy||generation!==this.generation)return;entry.busy=true;try{const data=await widget.poll();if(generation===this.generation){entry.last=data;widget.render(el,data);}}catch{if(generation===this.generation)widget.render(el,entry.last?{...entry.last,stale:true}:{label:id==='clock'?'Clock —':'Weather —',title:'Offline; no cached value',stale:true});}finally{entry.busy=false;}};entry.timer=this.timers.set(()=>void poll(),widget.intervalMs);void poll();}}
 destroy(){this.generation++;for(const entry of this.active.values()){this.timers.clear(entry.timer);entry.abort.abort();entry.el.remove();}this.active.clear();}
}
export function buildWidgetSlots():HTMLElement {const host=document.createElement('div');host.className='widget-slots';const slots=new WidgetSlots(host);const reload=()=>slots.sync(loadWidgets());reload();window.addEventListener('nova-widgets-changed',reload);window.addEventListener('storage',e=>{if(e.key===WIDGET_PREFS_KEY)reload();});window.addEventListener('beforeunload',()=>slots.destroy(),{once:true});return host;}
